-- Lieferspatz - PostgreSQL schema
-- Identifiers keep their original PascalCase, so they must always be
-- double-quoted in queries (Postgres folds unquoted names to lowercase).

DROP TABLE IF EXISTS "Checkout"       CASCADE;
DROP TABLE IF EXISTS "OrderDetails"   CASCADE;
DROP TABLE IF EXISTS "Cart"           CASCADE;
DROP TABLE IF EXISTS "Codes"          CASCADE;
DROP TABLE IF EXISTS "OrderTable"     CASCADE;
DROP TABLE IF EXISTS "MenuItem"       CASCADE;
DROP TABLE IF EXISTS "Restaurant"     CASCADE;
DROP TABLE IF EXISTS "Customer"       CASCADE;
DROP TABLE IF EXISTS "Account"        CASCADE;
-- Legacy link tables from the original SQLite dump (unused by the app).
DROP TABLE IF EXISTS "Serve"          CASCADE;
DROP TABLE IF EXISTS "AddItem"        CASCADE;
DROP TABLE IF EXISTS "Has"            CASCADE;


CREATE TABLE "Account" (
    "Username"  varchar(255) PRIMARY KEY,
    "Password"  varchar(255),
    "UserType"  varchar(20) NOT NULL
);

CREATE TABLE "Customer" (
    "CustomerID"  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Username"    varchar(255) UNIQUE REFERENCES "Account"("Username"),
    "FirstName"   varchar(255),
    "LastName"    varchar(255),
    "Address"     varchar(255),
    "PLZ"         varchar(10),
    "City"        varchar(255)
);

CREATE TABLE "Restaurant" (
    "RestaurantID"  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Username"      varchar(255) UNIQUE REFERENCES "Account"("Username"),
    "FirstName"     varchar(255),
    "LastName"      varchar(255),
    "Address"       varchar(255),
    "PLZ"           varchar(10),
    "City"          varchar(255),
    "Description"   varchar(255),
    "Picture"       varchar(1024),
    "OpeningTime"   varchar(8),
    "ClosingTime"   varchar(8)
);

CREATE TABLE "MenuItem" (
    "MenuItemID"    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RestaurantID"  integer REFERENCES "Restaurant"("RestaurantID"),
    "Name"          varchar(255),
    "Category"      varchar(255),
    "Description"   varchar(255),
    "Price"         numeric(10, 2),
    "Picture"       varchar(1024)
);

CREATE TABLE "Codes" (
    "RestaurantID"  integer REFERENCES "Restaurant"("RestaurantID"),
    "Code"          varchar(10)
);

CREATE TABLE "OrderTable" (
    "OrderID"         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Status"          varchar(255),
    "SubmissionTime"  timestamp,
    "ReviewedBy"      integer REFERENCES "Customer"("CustomerID"),
    "ReceivedBy"      integer REFERENCES "Restaurant"("RestaurantID")
);

CREATE TABLE "Cart" (
    "CartID"      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CustomerID"  integer REFERENCES "Customer"("CustomerID"),
    "ItemID"      integer REFERENCES "MenuItem"("MenuItemID"),
    "Quantity"    integer,
    "TotalPrice"  numeric(10, 2)
);

CREATE TABLE "OrderDetails" (
    "DetailID"    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "OrderID"     integer REFERENCES "OrderTable"("OrderID"),
    "ItemID"      integer REFERENCES "MenuItem"("MenuItemID"),
    "Quantity"    integer,
    "TotalPrice"  numeric(10, 2)
);

CREATE TABLE "Checkout" (
    "CartID"   integer,
    "OrderID"  integer REFERENCES "OrderTable"("OrderID")
);

CREATE INDEX "idx_menuitem_restaurant" ON "MenuItem" ("RestaurantID");
CREATE INDEX "idx_codes_restaurant"    ON "Codes" ("RestaurantID");
CREATE INDEX "idx_codes_code"          ON "Codes" ("Code");
CREATE INDEX "idx_cart_customer"       ON "Cart" ("CustomerID");
CREATE INDEX "idx_order_receivedby"    ON "OrderTable" ("ReceivedBy");
CREATE INDEX "idx_order_reviewedby"    ON "OrderTable" ("ReviewedBy");
CREATE INDEX "idx_orderdetails_order"  ON "OrderDetails" ("OrderID");
